/* The build: the app for the isolate, and the folder for the shell.
 *
 * The isolate half is yeetkit's own pipeline — routes, entry, Babel
 * for Solid's universal renderer, esbuild for one neutral bundle — run
 * with two of its three runtimes ruled out. A plugin has no browser,
 * so a `"use client"` island has nowhere to mount; and it has no Node
 * hub, so a `"use server"` call would wait forever. Both fail the
 * build with a message rather than failing the user at runtime.
 *
 * The shell half is a directory that is a complete Omarchy plugin:
 *
 *   manifest.json        the project's, with entryPoints and the
 *                        service kind filled in
 *   BarWidget.qml        entry points, generated
 *   Panel.qml
 *   Service.qml          runs the isolate
 *   app.js               the bundle `yeet run` executes
 *   bin/app.bpf.o        if the project has bpf/
 *   yeetkit/             the QML client and node vocabulary, copied —
 *                        a plugin folder may not contain symlinks
 *   README.md, LICENSE, preview.png   copied through if present
 */

import { access, cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { hasBpf, make, place } from "yeetkit/src/cli/bpf.mjs";
import { createBundler, entryModule } from "yeetkit/src/cli/bundle.mjs";
import { collectRoutes, renderRouteModule } from "yeetkit/src/cli/routes.mjs";

import { KINDS } from "./config.mjs";

const here = dirname(fileURLToPath(import.meta.url));
export const QML = join(here, "..", "..", "qml");

const exists = (path) => access(path).then(() => true, () => false);

/** Bundles `app/` into `.yeetkit/app.js`. Throws with the reasons on failure. */
export async function buildIsolate(config, { dev = false } = {}) {
  const { root, appDir, out, title, direct } = config;
  await mkdir(out, { recursive: true });

  let bpf = null;
  if (await hasBpf(root)) {
    const result = await make(root);
    if (!result.ok) throw new Error(`bpf build failed\n${result.output}`);
    bpf = result.output;
  }

  const collected = await collectRoutes(appDir);
  if (collected.routes.length === 0) throw new Error(`no page in ${appDir} — a plugin needs app/page.jsx`);
  const { code, summary } = renderRouteModule(collected, out);
  await writeFile(join(out, "routes.js"), code);
  await writeFile(join(out, "entry.jsx"), await entryModule({ title, appDir, out, direct }));

  const islands = new Set();
  const actions = new Set();
  const isolateFns = new Set();

  const bundler = await createBundler({
    entry: join(out, "entry.jsx"),
    outfile: join(out, "app.js"),
    dev,
    root,
    appDir,
    side: "server",
    islands,
    actions,
    isolateFns,
  });
  const result = await bundler.rebuild().catch((error) => error);
  await bundler.dispose();

  if (result?.errors?.length) {
    const lines = result.errors.map((error) => {
      const where = error.location ? ` (${error.location.file}:${error.location.line})` : "";
      return `  ${error.text}${where}`;
    });
    throw new Error(`build failed\n${lines.join("\n")}`);
  }

  if (islands.size > 0) {
    throw new Error(
      `"use client" has nowhere to run in a shell plugin — there is no browser.\n` +
        `  ${[...islands].join("\n  ")}\n` +
        `  Render it in the isolate instead: drop the directive.`,
    );
  }
  if (actions.size > 0) {
    throw new Error(
      `"use server" needs the Node hub, and a plugin runs without one.\n` +
        `  ${[...actions].join("\n  ")}\n` +
        `  Make it "use yeet" — the isolate has yeet.graph, yeet:bpf and yeet:ai — or shell out from QML.`,
    );
  }

  return { summary, isolateFns: [...isolateFns], bpf };
}

/** The Config.js the generated QML reads. */
export function configModule(config, { managed }) {
  const { manifest, wsPort, consolePort, direct } = config;
  return `.pragma library
// Generated by yeetkit-omarchy build. Edit yeetkit.config.js, not this.

var id = ${JSON.stringify(manifest.id)};
var name = ${JSON.stringify(manifest.name)};
var port = ${wsPort};
var consolePort = ${consolePort};
var direct = ${direct ? "true" : "false"};
/* Whether Service.qml runs the isolate. The dev server runs it itself
 * and writes this false, so the shell only ever connects. */
var managed = ${managed ? "true" : "false"};

var url = "ws://127.0.0.1:" + port + "/";
var viewUrl = direct ? "ws://127.0.0.1:" + consolePort + "/" : "";

function command(appPath) {
  var argv = ["yeet", "run", "-y", "-q", "-p", "tty:ws://127.0.0.1:" + port];
  if (direct) argv.push("-p", "console:ws://127.0.0.1:" + consolePort);
  argv.push(appPath);
  return argv;
}
`;
}

/** The manifest as the shell should see it. */
export function pluginManifest(config) {
  const { manifest, kinds } = config;
  const out = JSON.parse(JSON.stringify(manifest));
  out.kinds = [...new Set([...manifest.kinds, "service"])];
  out.entryPoints = { ...(manifest.entryPoints ?? {}) };
  for (const kind of kinds) out.entryPoints[KINDS[kind].entryPoint] = KINDS[kind].file;
  out.entryPoints.service = "Service.qml";
  if (kinds.includes("bar-widget")) {
    out.barWidget = {
      displayName: manifest.name,
      description: manifest.description,
      category: "Plugins",
      allowMultiple: false,
      ...(manifest.barWidget ?? {}),
    };
  }
  return out;
}

/* Writes the plugin folder at `target` from a finished isolate build.
 * Everything in it is regenerated except what the project supplies. */
export async function writePlugin(config, target, { managed }) {
  const { root, out, manifest, kinds } = config;
  await mkdir(target, { recursive: true });

  await cp(join(out, "app.js"), join(target, "app.js"));
  const bpfSize = await place(root, target);

  const runtime = join(target, "yeetkit");
  await rm(runtime, { recursive: true, force: true });
  await mkdir(join(runtime, "nodes"), { recursive: true });
  for (const file of ["Yeetkit.qml", "Protocol.js", "WebSocketTransport.qml"]) {
    await cp(join(QML, file), join(runtime, file));
  }
  for (const file of await readdir(join(QML, "nodes"))) {
    await cp(join(QML, "nodes", file), join(runtime, "nodes", file));
  }
  await writeFile(join(runtime, "Config.js"), configModule(config, { managed }));

  const fill = (text) =>
    text.replaceAll("__ID__", manifest.id).replaceAll("__NAME__", manifest.name.replaceAll('"', '\\"'));
  const entries = new Set(["Service.qml"]);
  for (const kind of kinds) {
    entries.add(KINDS[kind].file);
    if (kind === "bar-widget") entries.add("Panel.qml");
  }
  for (const file of entries) {
    await writeFile(join(target, file), fill(await readFile(join(QML, "entries", file), "utf8")));
  }

  await writeFile(join(target, "manifest.json"), JSON.stringify(pluginManifest(config), null, 2) + "\n");

  for (const file of ["README.md", "LICENSE", "preview.png"]) {
    if (await exists(join(root, file))) await cp(join(root, file), join(target, file));
  }

  return { entries: [...entries], bpfSize };
}

/** `yeetkit-omarchy build`: the whole thing, into `config.dist`. */
export async function build(config) {
  const built = await buildIsolate(config, { dev: false });
  const written = await writePlugin(config, config.dist, { managed: true });
  return { ...built, ...written };
}
