import QtQuick
import Quickshell
import qs.Ui
import "yeetkit" as Kit

// Generated by yeetkit-omarchy. The bar entry point: it attaches to the
// plugin's isolate (yeetkit/Isolate.qml starts it on first attach),
// shows whatever the app's <bar> element says, and hosts the panel the
// app's <panel> element fills — following the shape of the first-party
// clock so the shell's open/close/toggle routes land here.
BarWidget {
  id: root
  moduleName: "__ID__"

  readonly property bool opened: panelLoader.item ? panelLoader.item.opened === true : false
  readonly property bool popoutSwitchClosing: panelLoader.item ? panelLoader.item.popoutSwitchClosing === true : false
  readonly property bool hasPanel: !!client.regions.panel
  property Item barItem: client.regions.bar || null

  function open() { if (panelLoader.item && hasPanel) panelLoader.item.open() }
  function close() { if (panelLoader.item) panelLoader.item.close() }
  function toggle() { if (panelLoader.item && hasPanel) panelLoader.item.toggle() }
  function closeForPopoutSwitch() { if (panelLoader.item) panelLoader.item.closeForPopoutSwitch() }

  function injectPanel() {
    if (!panelLoader.item) return
    panelLoader.item.bar = root.bar
    panelLoader.item.anchorItem = holder
    panelLoader.item.hostWidget = root
    panelLoader.item.client = client
  }

  implicitWidth: holder.implicitWidth
  implicitHeight: holder.implicitHeight

  onBarChanged: injectPanel()

  Kit.Yeetkit {
    id: client
    bar: root.bar

    /* A left click on the bar item reaches the app as an event, and —
     * when the app has a panel — toggles it here, the way every bar
     * widget with a popup behaves. */
    onRegionEvent: function (name, type, payload) {
      if (name === "bar" && type === "click" && payload.button === 0 && root.hasPanel) root.toggle()
    }
  }

  onBarItemChanged: {
    if (!barItem) return
    barItem.parent = holder
    barItem.anchors.fill = holder
  }

  Item {
    id: holder
    anchors.fill: parent
    implicitWidth: root.barItem ? root.barItem.implicitWidth : placeholder.implicitWidth
    implicitHeight: root.barItem ? root.barItem.implicitHeight : placeholder.implicitHeight
  }

  /* Until the tree arrives — the isolate is still starting, or has
   * just restarted — a dimmed dot keeps the slot from collapsing. */
  WidgetButton {
    id: placeholder
    anchors.fill: parent
    bar: root.bar
    visible: !root.barItem
    dimmed: true
    keepSpace: true
    text: "·"
    tooltipText: "__NAME__ — waiting for the isolate"
    pressable: false
  }

  Loader {
    id: panelLoader
    active: true
    source: Qt.resolvedUrl("Panel.qml")
    visible: false
    onLoaded: {
      root.injectPanel()
      Qt.callLater(root.injectPanel)
    }
  }
}
