import QtQuick
import QtQuick.Effects
import Quickshell
import qs.Ui
import "yeetkit" as Kit
import "yeetkit/Config.js" as Config

// Generated by yeetkit-omarchy. The bar entry point: it attaches to the
// plugin's isolate (yeetkit/Isolate.qml starts it on first attach),
// shows whatever the app's <bar> element says, and hosts the panel the
// app's <panel> element fills — following the shape of the first-party
// clock so the shell's open/close/toggle routes land here.
BarWidget {
  id: root
  moduleName: "__ID__"

  readonly property bool opened: panelLoader.item ? panelLoader.item.opened === true : false
  readonly property bool popoutSwitchClosing: panelLoader.item ? panelLoader.item.popoutSwitchClosing === true : false
  readonly property bool hasPanel: !!client.regions.panel || Kit.Isolate.trouble !== ""
  property Item barItem: client.regions.bar || null

  function open() { if (panelLoader.item && hasPanel) panelLoader.item.open() }
  function close() { if (panelLoader.item) panelLoader.item.close() }
  function toggle() { if (panelLoader.item && hasPanel) panelLoader.item.toggle() }
  function closeForPopoutSwitch() { if (panelLoader.item) panelLoader.item.closeForPopoutSwitch() }

  function injectPanel() {
    if (!panelLoader.item) return
    panelLoader.item.bar = root.bar
    panelLoader.item.anchorItem = holder
    panelLoader.item.hostWidget = root
    panelLoader.item.client = client
  }

  implicitWidth: holder.implicitWidth
  implicitHeight: holder.implicitHeight

  onBarChanged: injectPanel()

  /** The client, reachable by the panel and by tests. */
  readonly property alias client: kit

  Kit.Yeetkit {
    id: kit
    bar: root.bar

    /* A left click on the bar item reaches the app as an event, and —
     * when the app has a panel — toggles it here, the way every bar
     * widget with a popup behaves. */
    onRegionEvent: function (name, type, payload) {
      if (name === "bar" && type === "click" && payload.button === 0 && root.hasPanel) root.toggle()
    }
  }

  onBarItemChanged: {
    if (!barItem) return
    barItem.parent = holder
    barItem.anchors.fill = holder
  }

  Item {
    id: holder
    anchors.fill: parent
    implicitWidth: root.barItem ? root.barItem.implicitWidth : placeholder.implicitWidth
    implicitHeight: root.barItem ? root.barItem.implicitHeight : placeholder.implicitHeight
  }

  /* Until the tree arrives — the isolate is still starting, or has
   * just restarted — a dimmed dot keeps the slot from collapsing. When
   * the reason it will never arrive is yeet itself, the dot gives way to
   * a label that says so and opens the panel, which carries the remedy. */
  WidgetButton {
    id: placeholder
    anchors.fill: parent
    bar: root.bar
    visible: !root.barItem
    dimmed: Kit.Isolate.trouble === ""
    keepSpace: true
    /* With a mark configured (yeetkit.config.js `barImage`), the slot
     * shows it drained of colour while the isolate is not up, with a
     * warning beside it when yeet itself is the reason. Without one, a
     * dot, or a label naming the trouble. */
    readonly property bool hasImage: Config.barImage !== ""
    labelVisible: !hasImage
    hasVisualContent: true
    fixedWidth: hasImage ? mark.implicitWidth + scaledHorizontalMargin * 2 : -1
    text: Kit.Isolate.trouble !== "" ? "⚠ yeet"
        : client.phase === "reconnecting" ? "…" : "·"
    /* Short: the placeholder sits at the bar's right edge, and the
     * shell lets a tooltip run past the screen. The panel carries the
     * commands. */
    tooltipText: Kit.Isolate.trouble === "missing"
        ? "yeet is not installed · click to install"
        : Kit.Isolate.trouble === "daemon"
        ? "yeetd is not running · click to start it"
        : "starting…"
    pressable: Kit.Isolate.trouble !== ""
    onPressed: root.toggle()

    Row {
      id: mark
      anchors.centerIn: parent
      spacing: 4
      visible: placeholder.hasImage

      Image {
        id: markImage
        source: placeholder.hasImage ? Qt.resolvedUrl(Config.barImage) : ""
        height: placeholder.barSize - 8
        width: height
        anchors.verticalCenter: parent.verticalCenter
        fillMode: Image.PreserveAspectFit
        smooth: true
        mipmap: true
        visible: false
      }
      /* Greyed: no saturation, and faint. */
      MultiEffect {
        source: markImage
        width: markImage.width
        height: markImage.height
        anchors.verticalCenter: parent.verticalCenter
        saturation: -1
        brightness: -0.1
        opacity: 0.45
      }

      Text {
        visible: Kit.Isolate.trouble !== ""
        anchors.verticalCenter: parent.verticalCenter
        text: "⚠"
        color: placeholder.foreground
        font.family: placeholder.fontFamily
        font.pixelSize: placeholder.fontSize
        renderType: Text.NativeRendering
      }
    }
  }

  Loader {
    id: panelLoader
    active: true
    source: Qt.resolvedUrl("Panel.qml")
    visible: false
    onLoaded: {
      root.injectPanel()
      Qt.callLater(root.injectPanel)
    }
  }
}
