import QtQuick
import Quickshell
import qs.Commons
import qs.Ui

// Generated by yeetkit-omarchy. The popup under the bar item: a
// KeyboardPanel framing the app's <panel> element. Escape closes it,
// Tab walks to the neighbouring popup, and every other key the catcher
// sees is forwarded to the isolate for `onKey`.
Panel {
  id: root
  moduleName: "__ID__"
  manageIpc: false

  property var anchorItem: null
  property var hostWidget: null
  property var client: null

  property Item region: client ? (client.regions.panel || null) : null

  function open() { root.controller.show() }
  function close() { root.controller.hide() }
  function switchPanel(direction) {
    if (root.bar && typeof root.bar.switchPanelFrom === "function")
      return root.bar.switchPanelFrom(root.hostWidget || root, direction)
    return false
  }

  onOpenedChanged: if (region) region.shellOpened(opened)

  onRegionChanged: {
    if (!region) return
    region.parent = content
    region.shellOpened(root.opened)
    region.openRequested.connect(function (wanted) { wanted ? root.open() : root.close() })
  }

  KeyboardPanel {
    id: panel
    anchorItem: root.anchorItem
    owner: root.hostWidget || root
    bar: root.bar
    open: root.opened && !!root.region
    focusTarget: keyCatcher
    contentWidth: panel.fittedContentWidth(root.region ? root.region.contentWidth : Style.space(240))
    contentHeight: panel.fittedContentHeight(content.implicitHeight)

    PanelKeyCatcher {
      id: keyCatcher
      anchors.fill: parent
      blocked: root.client ? root.client.inputFocus : false

      onCloseRequested: root.close()
      onTabRequested: function (direction) { root.switchPanel(direction) }
      onMoveRequested: function (dx, dy) {
        if (!root.client) return
        root.client.key({ key: dy > 0 ? "ArrowDown" : dy < 0 ? "ArrowUp" : dx > 0 ? "ArrowRight" : "ArrowLeft" })
      }
      onActivateRequested: if (root.client) root.client.key({ key: "Enter" })
      onDeleteRequested: if (root.client) root.client.key({ key: "Delete" })
      onTextKey: function (text) { if (root.client) root.client.key({ key: text }) }

      Item {
        id: content
        width: parent.width
        implicitHeight: root.region ? root.region.implicitHeight : waiting.implicitHeight
        Text {
          id: waiting
          visible: !root.region
          text: "waiting for the isolate…"
          color: Color.muted
          font.family: Style.font.family
          font.pixelSize: Style.font.body
        }
      }
    }
  }
}
