import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Ui
import "yeetkit" as Kit

// Generated by yeetkit-omarchy. The popup under the bar item: a
// KeyboardPanel framing the app's <panel> element. Escape closes it,
// Tab walks to the neighbouring popup, and every other key the catcher
// sees is forwarded to the isolate for `onKey`.
//
// Until the isolate's tree arrives the panel stands in for it. If `yeet`
// is missing or its daemon is down the run can never come up, so the
// stand-in carries what to do about it rather than a spinner that will
// never resolve.
Panel {
  id: root
  moduleName: "__ID__"
  manageIpc: false

  property var anchorItem: null
  property var hostWidget: null
  property var client: null

  /* A labelled line in the stand-in: what to do, and the command or
   * link that does it. */
  /* A labelled line in the stand-in. The value is a read-only TextEdit
   * rather than a Text so an install command can actually be selected
   * and copied, which is the whole point of showing it. */
  property Process opener: Process {}

  function openUrl(url) {
    opener.command = ["xdg-open", String(url)]
    opener.running = true
  }

  component Section: Column {
    id: section
    property string label: ""
    property string value: ""
    property bool copyable: false
    property color valueColor: Color.popups.text
    property bool copied: false
    spacing: Style.spacing.xxs

    /* TextEdit.copy() puts the selection on the clipboard, so the
     * button selects the line, copies it and drops the selection
     * again — no helper process, nothing to install. */
    function copyValue() {
      field.selectAll()
      field.copy()
      field.deselect()
      section.copied = true
      revert.restart()
    }

    Timer {
      id: revert
      interval: 1500
      onTriggered: section.copied = false
    }

    Row {
      width: section.width
      spacing: Style.spacing.sm

      Text {
        text: section.label
        color: Color.popups.text
        font.family: Style.font.family
        font.pixelSize: Style.font.bodySmall
        font.bold: true
      }

      Button {
        visible: section.copyable
        text: section.copied ? "copied" : "copy"
        foreground: Color.muted
        fontSize: Style.font.bodySmall
        horizontalPadding: Style.spacing.xs
        verticalPadding: 0
        tooltipText: "Copy to the clipboard"
        onClicked: section.copyValue()
      }
    }

    TextEdit {
      id: field
      width: section.width
      readOnly: true
      selectByMouse: true
      textFormat: TextEdit.PlainText
      wrapMode: TextEdit.WrapAnywhere
      text: section.value
      color: section.valueColor
      font.family: Style.font.family
      font.pixelSize: Style.font.body
    }
  }

  property Item region: client ? (client.regions.panel || null) : null

  function open() { root.controller.show() }
  function close() { root.controller.hide() }
  function switchPanel(direction) {
    if (root.bar && typeof root.bar.switchPanelFrom === "function")
      return root.bar.switchPanelFrom(root.hostWidget || root, direction)
    return false
  }

  onOpenedChanged: if (region) region.shellOpened(opened)

  onRegionChanged: {
    if (!region) return
    region.parent = content
    region.shellOpened(root.opened)
    region.openRequested.connect(function (wanted) { wanted ? root.open() : root.close() })
  }

  KeyboardPanel {
    id: panel
    anchorItem: root.anchorItem
    owner: root.hostWidget || root
    bar: root.bar
    /* Openable with no tree as well, so the stand-in explaining a
     * missing yeet can actually be read. */
    open: root.opened && (!!root.region || Kit.Isolate.trouble !== "")
    focusTarget: keyCatcher
    /* With no tree the page cannot say how wide it wants to be, and the
     * stand-in has an install command in it — at the old 240 that
     * command wrapped mid-line, which is no use to copy. */
    contentWidth: panel.fittedContentWidth(root.region ? root.region.contentWidth : Style.space(400))
    contentHeight: panel.fittedContentHeight(content.implicitHeight)

    PanelKeyCatcher {
      id: keyCatcher
      anchors.fill: parent
      blocked: root.client ? root.client.inputFocus : false

      onCloseRequested: root.close()
      onTabRequested: function (direction) { root.switchPanel(direction) }
      onMoveRequested: function (dx, dy) {
        if (!root.client) return
        root.client.key({ key: dy > 0 ? "ArrowDown" : dy < 0 ? "ArrowUp" : dx > 0 ? "ArrowRight" : "ArrowLeft" })
      }
      onActivateRequested: if (root.client) root.client.key({ key: "Enter" })
      onDeleteRequested: if (root.client) root.client.key({ key: "Delete" })
      onTextKey: function (text) { if (root.client) root.client.key({ key: text }) }

      Item {
        id: content
        width: parent.width
        implicitHeight: root.region ? root.region.implicitHeight : help.implicitHeight

        Column {
          id: help
          visible: !root.region
          width: parent.width
          spacing: Style.spacing.md

          readonly property string trouble: Kit.Isolate.trouble

          Text {
            width: parent.width
            wrapMode: Text.WordWrap
            text: help.trouble === "missing" ? "yeet is not installed"
                : help.trouble === "daemon" ? "yeetd is not running"
                : "Waiting for the isolate…"
            color: help.trouble === "" ? Color.muted : Color.popups.text
            font.family: Style.font.family
            font.pixelSize: Style.font.subtitle
            font.bold: help.trouble !== ""
          }

          TextEdit {
            width: parent.width
            visible: help.trouble !== ""
            readOnly: true
            selectByMouse: true
            textFormat: TextEdit.PlainText
            wrapMode: TextEdit.WordWrap
            text: "__NAME__ draws from a yeet isolate, so it needs yeet installed and its daemon running."
            color: Color.muted
            font.family: Style.font.family
            font.pixelSize: Style.font.bodySmall
          }

          Section {
            width: parent.width
            visible: help.trouble === "daemon"
            label: "Start"
            value: "sudo systemctl enable --now yeetd"
            copyable: true
          }

          Section {
            width: parent.width
            visible: help.trouble === "missing"
            label: "Install"
            value: "curl -fsSL https://yeet.cx | sh"
            copyable: true
          }

          Row {
            visible: help.trouble !== ""
            spacing: Style.spacing.lg

            Text {
              visible: help.trouble === "missing"
              textFormat: Text.StyledText
              text: "<a href=\"https://yeet.cx/docs/install/manual-installation\">Manual Install</a>"
              linkColor: Color.accent
              color: Color.accent
              font.family: Style.font.family
              font.pixelSize: Style.font.bodySmall
              onLinkActivated: function (link) { root.openUrl(link) }
              HoverHandler { cursorShape: Qt.PointingHandCursor }
            }

            Text {
              textFormat: Text.StyledText
              text: "<a href=\"https://yeet.cx/docs/install/\">Docs</a>"
              linkColor: Color.accent
              color: Color.accent
              font.family: Style.font.family
              font.pixelSize: Style.font.bodySmall
              onLinkActivated: function (link) { root.openUrl(link) }
              HoverHandler { cursorShape: Qt.PointingHandCursor }
            }
          }
        }
      }
    }
  }
}
