import QtQuick
import Quickshell.Io
import "yeetkit/Config.js" as Config

// Generated by yeetkit-omarchy. The headless half: one isolate per
// plugin, supervised here rather than by a bar widget, because a bar
// exists once per monitor and the isolate must not. `yeet run` binds
// the app's tty to a loopback WebSocket; the widget and its panel dial
// it. In development the dev server runs the isolate instead and this
// stays idle (Config.managed is false).
Item {
  id: root

  property var shell: null

  readonly property string appPath: String(Qt.resolvedUrl("app.js")).replace(/^file:\/\//, "")

  Process {
    id: isolate
    command: Config.command(root.appPath)
    running: Config.managed
    stdout: SplitParser {
      onRead: function (line) { console.log("[" + Config.id + "] " + line) }
    }
    stderr: SplitParser {
      onRead: function (line) { console.warn("[" + Config.id + "] " + line) }
    }
    /* The daemon tears the portal down a moment after the run exits,
     * so an immediate respawn is met with "already mounted". */
    onExited: function (code, status) { if (Config.managed) respawn.restart() }
  }

  Timer {
    id: respawn
    interval: 1500
    repeat: false
    onTriggered: isolate.running = true
  }
}
